In [ ]:
from openai import OpenAI
from os import getenv

# gets API Key from environment variable OPENAI_API_KEY
client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key="",
)

completion = client.chat.completions.create(
    model="liquid/lfm-40b:free",
    messages=[{"role": "user", "content": "What is the meaning of life?"}],
)
print(completion.choices[0].message.content)

In [16]:
import pandas as pd

df = pd.read_csv(
    "/Users/manojkl/Documents/Cost_To_Consumers-CTC/AGI/GovSpendBotAgent/src/Dataset/WikiTableQuestions/csv/200-csv/11.csv"
)
df

,Award,Category,Nominee,Result
0,"Academy Awards, 1972",Best Picture,Phillip D'Antoni,Won
1,"Academy Awards, 1972",Best Director,William Friedkin,Won
2,"Academy Awards, 1972",Best Actor,Gene Hackman,Won
3,"Academy Awards, 1972",Best Adapted Screenplay,Ernest Tidyman,Won
4,"Academy Awards, 1972",Film Editing,Gerald B. Greenberg,Won
5,"Academy Awards, 1972",Best Supporting Actor,Roy Scheider,Nominated
6,"Academy Awards, 1972",Best Cinematography,Owen Roizman,Nominated
7,"Academy Awards, 1972",Best Sound,Theodore Soderberg\nChristopher Newman,Nominated
8,"American Cinema Editors, 1972",Best Edited Feature Film,Gerald B. Greenberg,Nominated
9,"BAFTA, 1972",Best Actor,Gene Hackman,Won
10,"BAFTA, 1972",Best Film Editing,Gerald B. Greenberg,Won
11,"BAFTA, 1972",Best Direction,William Friedkin,Nominated
12,"BAFTA, 1972",Best Film,Philip D'Antoni,Nominated
13,"BAFTA, 1972",Best Sound Track,Christopher Newman\nTheodore Soderberg,Nominated
14,"David di Donatello Award, 1972",Best Foreign Film,Philip D'Antoni,Won
15,"Directors Guild of America, 1972",Outstanding Directorial Achievement,William Friedkin,Won
16,"Edgar Allan Poe Awards, 1972",Best Motion Picture,Ernest Tidyman,Won
17,"Golden Globe Awards, 1972",Best Motion Picture,Phillip D'Antoni,Won
18,"Golden Globe Awards, 1972",Best Director,William Friedkin,Won
19,"Golden Globe Awards, 1972",Best Actor,Gene Hackman,Won
20,"Golden Globe Awards, 1972",Best Screenplay,Ernest Tidyman,Nominated
21,"Kansas City Film Critics Circle, 1972",Best Actor,Gene Hackman,Won
22,"Kansas City Film Critics Circle, 1972",Best Film,Ernest Tidyman,Won
23,"National Society of Film Critics, 1972",Best Actor,Gene Hackman,Nominated
24,"New York Film Critics Circle, 1971",Best Actor,Gene Hackman,Won
25,"New York Film Critics Circle, 1971",Best Film,Ernest Tidyman,Nominated
26,"Writers Guild of America, 1972",Best Drama Adaptation,Ernest Tidyman,Nominated

In [22]:
import pandas as pd
from llama_index.llms.openrouter import OpenRouter
from llama_index.core.llms import ChatMessage

# Initialize OpenRouter (as you already have)
llm = OpenRouter(
    api_key="",
    max_tokens=256,
    context_window=4096,
    model="meta-llama/llama-3.1-70b-instruct:free",
    # model="undi95/toppy-m-7b:free",
)

# Read the CSV file using pandas (or use other methods to extract data)
# df = pd.read_csv("/Users/manojkl/Downloads/expense_data_1.csv")

# Convert the DataFrame into a text format that can be used in prompts
csv_text = df.to_string(index=False)  # Converts to string without row indices

# Prepare a message to pass to the model (assuming you are using a prompt-based approach)
user_message = ChatMessage(
    role="user",
    content=f"Here is the data from my CSV:\n{csv_text}\n what is the total food amount on date 3/1/2022? Don't give me program instead analyze the data and give me result, also give python program to plot food cost over the time",
)

# Use the LLM to process the message
response = llm.chat([user_message])

# Print the model's response
print(response)

assistant: Based on the data provided, the total food amount on date 3/1/2022 is:

- Dinner: 78.00
- Snacks: 67.00

Total food amount on 3/1/2022: 78.00 + 67.00 = 145.00

Here is a Python program to plot the food cost over time:

```python
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# Load the data
data = {
    "Date": ["3/2/2022 10:11", "3/2/2022 10:11", "3/1/2022 19:50", "3/1/2022 18:56", "3/1/2022 18:22", "3/1/2022 18:22", "3/1/2022 18:21", "2/28/2022 11:56", "2/28/2022 11:45", "2/27/2022 15:29", "2/26/2022 20:16", "2/26/2022 17:37",

In [ ]:
# assistant: The total food amount on date 3/1/2022 is 381.00 INR. Here is the breakdown:
# - Dinner: 78.00 INR
# - Snacks: 67.00 INR

# So, the total food expense on 3/1/2022 is 145.00 INR.

# Date: 3/1/2022

In [95]:
from chain_of_table_pack.llama_index.packs.tables.chain_of_table.base import (
    ChainOfTableQueryEngine,
    serialize_table,
)

In [1]:
# /Users/manojkl/Documents/Cost_To_Consumers-CTC/AGI/GovSpendBotAgent/src/experiments/Chain_Of_Table/base.py

from base_new import ChainOfTableQueryEngine, serialize_table

In [2]:
from llama_index.llms.openrouter import OpenRouter
from llama_index.core.llms import ChatMessage

llm = OpenRouter(
    api_key="",
    max_tokens=256,
    context_window=4096,
    model="undi95/toppy-m-7b:free",
)

message = ChatMessage(role="user", content="Tell me a joke")
resp = llm.chat([message])
print(resp)

/Users/manojkl/miniconda3/envs/llm/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

assistant: Why don't scientists trust atoms? Because they make up everything!

In [19]:
import pandas as pd
df = pd.read_csv("/Users/manojkl/Downloads/expense_data_1.csv")
df

,Date,Account,Category,Subcategory,Note,INR,Income/Expense,Note.1,Amount,Currency,Account.1
0,3/2/2022 10:11,CUB - online payment,Food,NaN,Brownie,50.0,Expense,NaN,50.0,INR,50.0
1,3/2/2022 10:11,CUB - online payment,Other,NaN,To lended people,300.0,Expense,NaN,300.0,INR,300.0
2,3/1/2022 19:50,CUB - online payment,Food,NaN,Dinner,78.0,Expense,NaN,78.0,INR,78.0
3,3/1/2022 18:56,CUB - online payment,Transportation,NaN,Metro,30.0,Expense,NaN,30.0,INR,30.0
4,3/1/2022 18:22,CUB - online payment,Food,NaN,Snacks,67.0,Expense,NaN,67.0,INR,67.0
...,...,...,...,...,...,...,...,...,...,...,...
272,11/22/2021 14:16,CUB - online payment,Food,NaN,Dinner,90.0,Expense,NaN,90.0,INR,90.0
273,11/22/2021 14:16,CUB - online payment,Food,NaN,Lunch with company,97.0,Expense,NaN,97.0,INR,97.0
274,11/21/2021 17:07,CUB - online payment,Transportation,NaN,Rapido,130.0,Expense,NaN,130.0,INR,130.0
275,11/21/2021 15:50,CUB - online payment,Food,NaN,Lunch,875.0,Expense,NaN,875.0,INR,875.0
276,11/21/2021 13:30,CUB - online payment,Other,NaN,Got from gobi,2000.0,Income,NaN,2000.0,INR,2000.0

In [23]:
# Initialize the query engine with the service context
query_engine = ChainOfTableQueryEngine(
    df, llm=llm, verbose=True
)

print("Hi")
# Query the engine
# response = query_engine.custom_query("Who nominated Best Sound in the 1972 Academy Awards?")
response = query_engine.custom_query("what is the total food amount on date 3/1/2022?")
print(response)

Hi
Run chain of table query engine.
Hi
> Iteration: 0
> Current table:
col : Date | Account | Category | Subcategory | Note | INR | Income/Expense | Note.1 | Amount | Currency | Account.1
row 1 : 3/2/2022 10:11 | CUB - online payment | Food | nan | Brownie | 50.0 | Expense | nan | 50.0 | INR | 50.0
row 2 : 3/2/2022 10:11 | CUB - online payment | Other | nan | To lended people | 300.0 | Expense | nan | 300.0 | INR | 300.0
row 3 : 3/1/2022 19:50 | CUB - online payment | Food | nan | Dinner | 78.0 | Expense | nan | 78.0 | INR | 78.0
row 4 : 3/1/2022 18:56 | CUB - online payment | Transportation | nan | Metro | 30.0 | Expense | nan | 30.0 | INR | 30.0
row 5 : 3/1/2022 18:22 | CUB - online payment | Food | nan | Snacks | 67.0 | Expense | nan | 67.0 | INR | 67.0
row 6 : 3/1/2022 18:22 | CUB - online payment | Other | nan | From vicky | 100.0 | Income | nan | 100.0 | INR | 100.0
row 7 : 3/1/2022 18:21 | CUB - online payment | Other | nan | From dad | 500.0 | Income | nan | 500.0 | INR | 500.0
row 8 : 2/28/2022 11:56 | CUB - online payment | Food | nan | Pizza | 339.15 | Expense | nan | 339.15 | INR | 339.15
row 9 : 2/28/2022 11:45 | CUB - online payment | Other | nan | From kumara | 200.0 | Income | nan | 200.0 | INR | 200.0
row 10 : 2/27/2022 15:29 | CUB - online payment | Food | nan | Lunch | 243.0 | Expense | nan | 243.0 | INR | 243.0
row 11 : 2/26/2022 20:16 | CUB - online payment | Food | nan | nan | 25.0 | Expense | nan | 25.0 | INR | 25.0
row 12 : 2/26/2022 17:37 | CUB - online payment | Other | nan | From dad | 1500.0 | Income | nan | 1500.0 | INR | 1500.0
row 13 : 2/26/2022 17:37 | CUB - online payment | Other | nan | To karthi | 100.0 | Expense | nan | 100.0 | INR | 100.0
row 14 : 2/26/2022 16:01 | CUB - online payment | Social Life | nan | nan | 1700.0 | Expense | nan | 1700.0 | INR | 1700.0
row 15 : 2/26/2022 14:07 | CUB - online payment | Food | nan | Snacks | 40.0 | Expense | nan | 40.0 | INR | 40.0
row 16 : 2/26/2022 1:39 | CUB - online payment | Food | nan | Tea lights | 84.0 | Expense | nan | 84.0 | INR | 84.0
row 17 : 2/25/2022 12:08 | CUB - online payment | Food | nan | nan | 33.0 | Expense | nan | 33.0 | INR | 33.0
row 18 : 2/24/2022 22:32 | CUB - online payment | Household | nan | nan | 303.0 | Expense | nan | 303.0 | INR | 303.0
row 19 : 2/24/2022 22:21 | CUB - online payment | Food | nan | Creamstone | 289.0 | Expense | nan | 289.0 | INR | 289.0
row 20 : 2/24/2022 19:15 | CUB - online payment | Food | nan | Tamen | 324.7 | Expense | nan | 324.7 | INR | 324.7
row 21 : 2/23/2022 17:35 | CUB - online payment | Apparel | nan | Hoodie for gobi | 399.0 | Expense | nan | 399.0 | INR | 399.0
row 22 : 2/23/2022 16:06 | CUB - online payment | Food | nan | Eggs | 83.0 | Expense | nan | 83.0 | INR | 83.0
row 23 : 2/23/2022 12:38 | CUB - online payment | Apparel | nan | Earphone | 399.0 | Expense | nan | 399.0 | INR | 399.0
row 24 : 2/22/2022 6:33 | CUB - online payment | Transportation | nan | Auto to laxmi mills | 120.0 | Expense | nan | 120.0 | INR | 120.0
row 25 : 2/21/2022 22:15 | CUB - online payment | Transportation | nan | It better be worth it | 1300.0 | Expense | nan | 1300.0 | INR | 1300.0
row 26 : 2/21/2022 16:06 | CUB - online payment | Transportation | nan | Travel to koyambedu | 138.0 | Expense | nan | 138.0 | INR | 138.0
row 27 : 2/21/2022 15:40 | CUB - online payment | Household | nan | Stuffs | 336.0 | Expense | nan | 336.0 | INR | 336.0
row 28 : 2/21/2022 15:38 | CUB - online payment | Transportation | nan | Train cbe to chn | 201.8 | Expense | nan | 201.8 | INR | 201.8
row 29 : 2/20/2022 15:24 | CUB - online payment | Food | nan | Lunch | 200.0 | Expense | nan | 200.0 | INR | 200.0
row 30 : 2/19/2022 23:03 | CUB - online payment | Food | nan | Random stuff for drinks | 111.0 | Expense | nan | 111.0 | INR | 111.0
row 31 : 2/19/2022 21:57 | CUB - online payment | Food | nan | Snacks | 250.0 | Expense | nan | 250.0 | INR | 250.0
row 32 : 2/19/2022 21:35 | CUB - online payment | Transportation | nan | Bus ticket | 1575.0 | Expense | nan | 1575.0 | INR | 1575.0
row 33 : 2/19/2022 20:45 | CUB - online payment | Transportation | nan | Took from sbi | 200.0 | Expense | nan | 200.0 | INR | 200.0
row 34 : 2/19/2022 20:45 | CUB - online payment | Food | nan | Ramen with gobi | 380.0 | Expense | nan | 380.0 | INR | 380.0
row 35 : 2/19/2022 8:26 | CUB - online payment | Transportation | nan | Metro | 60.0 | Expense | nan | 60.0 | INR | 60.0
row 36 : 2/19/2022 6:27 | CUB - online payment | Other | nan | To auto anna | 50.0 | Expense | nan | 50.0 | INR | 50.0
row 37 : 2/19/2022 6:18 | CUB - online payment | Transportation | nan | To egmore | 270.0 | Expense | nan | 270.0 | INR | 270.0
row 38 : 2/18/2022 23:01 | CUB - online payment | Food | nan | Kfc dinner | 348.0 | Expense | nan | 348.0 | INR | 348.0
row 39 : 2/17/2022 13:11 | CUB - online payment | Food | nan | Lunch | 80.0 | Expense | nan | 80.0 | INR | 80.0
row 40 : 2/16/2022 16:57 | CUB - online payment | Food | nan | Side dishes | 165.0 | Expense | nan | 165.0 | INR | 165.0
row 41 : 2/16/2022 16:57 | CUB - online payment | Food | nan | Kfc  | 475.0 | Expense | nan | 475.0 | INR | 475.0
row 42 : 2/13/2022 21:54 | CUB - online payment | Social Life | nan | Games  | 100.0 | Expense | nan | 100.0 | INR | 100.0
row 43 : 2/12/2022 21:20 | CUB - online payment | Food | nan | Dinner with aravind and buddies | 491.0 | Expense | nan | 491.0 | INR | 491.0
row 44 : 2/12/2022 16:04 | CUB - online payment | Household | nan | Mirror | 70.0 | Expense | nan | 70.0 | INR | 70.0
row 45 : 2/12/2022 14:48 | CUB - online payment | Food | nan | Lunch | 80.0 | Expense | nan | 80.0 | INR | 80.0
row 46 : 2/12/2022 14:47 | CUB - online payment | Other | nan | From dad | 10000.0 | Income | nan | 10000.0 | INR | 10000.0
row 47 : 2/11/2022 22:41 | CUB - online payment | Food | nan | Dinner with aravind | 373.0 | Expense | nan | 373.0 | INR | 373.0
row 48 : 2/10/2022 20:15 | CUB - online payment | Food | nan | Kfc dinner | 641.0 | Expense | nan | 641.0 | INR | 641.0
row 49 : 2/8/2022 10:37 | CUB - online payment | Other | nan | From dad | 1000.0 | Income | nan | 1000.0 | INR | 1000.0
row 50 : 2/8/2022 9:18 | CUB - online payment | Household | nan | Bean bag | 2099.0 | Expense | nan | 2099.0 | INR | 2099.0
row 51 : 2/7/2022 7:08 | CUB - online payment | Transportation | nan | Auto to Gobi's place | 214.0 | Expense | nan | 214.0 | INR | 214.0
row 52 : 2/6/2022 18:32 | CUB - online payment | Food | nan | Cakepark | 125.0 | Expense | nan | 125.0 | INR | 125.0
row 53 : 2/6/2022 17:53 | CUB - online payment | Food | nan | To kumara | 150.0 | Expense | nan | 150.0 | INR | 150.0
row 54 : 2/6/2022 17:52 | CUB - online payment | Transportation | nan | To chennai | 1000.0 | Expense | nan | 1000.0 | INR | 1000.0
row 55 : 2/6/2022 16:41 | CUB - online payment | Other | nan | Salary from dad | 5000.0 | Income | nan | 5000.0 | INR | 5000.0
row 56 : 2/6/2022 16:40 | CUB - online payment | Other | nan | To gobi | 1500.0 | Expense | nan | 1500.0 | INR | 1500.0
row 57 : 2/4/2022 20:28 | CUB - online payment | Food | nan | Shawarma | 80.0 | Expense | nan | 80.0 | INR | 80.0
row 58 : 2/3/2022 14:53 | CUB - online payment | Food | nan | Good soup | 50.0 | Expense | nan | 50.0 | INR | 50.0
row 59 : 2/3/2022 8:59 | CUB - online payment | Other | nan | To gowdham | 150.0 | Expense | nan | 150.0 | INR | 150.0
row 60 : 2/2/2022 20:15 | CUB - online payment | Food | nan | Parotta | 120.0 | Expense | nan | 120.0 | INR | 120.0
row 61 : 2/2/2022 20:14 | CUB - online payment | Other | nan | From dad | 500.0 | Income | nan | 500.0 | INR | 500.0
row 62 : 1/31/2022 8:44 | CUB - online payment | Transportation | nan | Vnr to apk | 50.0 | Expense | nan | 50.0 | INR | 50.0
row 63 : 1/31/2022 8:27 | CUB - online payment | Other | nan | To vicky | 200.0 | Expense | nan | 200.0 | INR | 200.0
row 64 : 1/31/2022 8:26 | CUB - online payment | Transportation | nan | To ksr station | 153.0 | Expense | nan | 153.0 | INR | 153.0
row 65 : 1/30/2022 19:17 | CUB - online payment | Food | nan | Dinner | 155.0 | Expense | nan | 155.0 | INR | 155.0
row 66 : 1/30/2022 19:01 | CUB - online payment | Food | nan | Cycle gap  | 120.0 | Expense | nan | 120.0 | INR | 120.0
row 67 : 1/30/2022 12:28 | CUB - online payment | Food | nan | Brunch | 105.0 | Expense | nan | 105.0 | INR | 105.0
row 68 : 1/29/2022 21:56 | CUB - online payment | Transportation | nan | Rapido to pg | 44.0 | Expense | nan | 44.0 | INR | 44.0
row 69 : 1/29/2022 14:44 | CUB - online payment | Other | nan | Sent to barath | 100.0 | Expense | nan | 100.0 | INR | 100.0
row 70 : 1/28/2022 21:58 | CUB - online payment | Food | nan | Banana | 10.0 | Expense | nan | 10.0 | INR | 10.0
row 71 : 1/28/2022 14:23 | CUB - online payment | Food | nan | Lunch with company | 138.0 | Expense | nan | 138.0 | INR | 138.0
row 72 : 1/27/2022 21:25 | CUB - online payment | Transportation | nan | Rapido to pg | 43.0 | Expense | nan | 43.0 | INR | 43.0
row 73 : 1/27/2022 13:41 | CUB - online payment | Other | nan | To vicky | 300.0 | Expense | nan | 300.0 | INR | 300.0
row 74 : 1/27/2022 13:41 | CUB - online payment | Other | nan | To vishnu | 100.0 | Expense | nan | 100.0 | INR | 100.0
row 75 : 1/27/2022 13:39 | CUB - online payment | Food | nan | Zinger box meal | 279.0 | Expense | nan | 279.0 | INR | 279.0
row 76 : 1/27/2022 13:38 | CUB - online payment | Other | nan | From vicky | 300.0 | Income | nan | 300.0 | INR | 300.0
row 77 : 1/27/2022 13:38 | CUB - online payment | Other | nan | From dad | 1500.0 | Income | nan | 1500.0 | INR | 1500.0
row 78 : 1/26/2022 17:45 | CUB - online payment | Food | nan | Snacks | 115.0 | Expense | nan | 115.0 | INR | 115.0
row 79 : 1/26/2022 17:45 | CUB - online payment | Other | nan | Vishnu 100 gowdham 25 | 125.0 | Income | nan | 125.0 | INR | 125.0
row 80 : 1/26/2022 16:52 | CUB - online payment | Food | nan | Paani poori | 25.0 | Expense | nan | 25.0 | INR | 25.0
row 81 : 1/25/2022 13:35 | CUB - online payment | Food | nan | Kfc date with myself | 259.0 | Expense | nan | 259.0 | INR | 259.0
row 82 : 1/25/2022 10:23 | CUB - online payment | Food | nan | Lemon tea | 18.0 | Expense | nan | 18.0 | INR | 18.0
row 83 : 1/25/2022 9:20 | CUB - online payment | Transportation | nan | Train to vnr | 325.0 | Expense | nan | 325.0 | INR | 325.0
row 84 : 1/24/2022 20:17 | CUB - online payment | Food | nan | Snack | 40.0 | Expense | nan | 40.0 | INR | 40.0
row 85 : 1/24/2022 14:08 | CUB - online payment | Food | nan | Lunch with company | 133.0 | Expense | nan | 133.0 | INR | 133.0
row 86 : 1/23/2022 21:45 | CUB - online payment | Food | nan | Pepsi | 40.0 | Expense | nan | 40.0 | INR | 40.0
row 87 : 1/23/2022 21:41 | CUB - online payment | Food | nan | Dinner | 465.0 | Expense | nan | 465.0 | INR | 465.0
row 88 : 1/23/2022 21:29 | CUB - online payment | Food | nan | Sent to vicky | 300.0 | Expense | nan | 300.0 | INR | 300.0
row 89 : 1/23/2022 21:29 | CUB - online payment | Food | nan | Lunch | 302.0 | Expense | nan | 302.0 | INR | 302.0
row 90 : 1/23/2022 21:29 | CUB - online payment | Other | nan | From vicky | 310.0 | Income | nan | 310.0 | INR | 310.0
row 91 : 1/23/2022 21:27 | CUB - online payment | Food | nan | Snacks with preethi and azar | 176.0 | Expense | nan | 176.0 | INR | 176.0
row 92 : 1/23/2022 21:27 | CUB - online payment | Social Life | nan | Badminton | 200.0 | Expense | nan | 200.0 | INR | 200.0
row 93 : 1/23/2022 21:27 | CUB - online payment | Other | nan | From dad | 2000.0 | Income | nan | 2000.0 | INR | 2000.0
row 94 : 1/21/2022 14:22 | CUB - online payment | Food | nan | Lunch with company | 188.0 | Expense | nan | 188.0 | INR | 188.0
row 95 : 1/21/2022 11:47 | CUB - online payment | Food | nan | Snacks | 37.0 | Expense | nan | 37.0 | INR | 37.0
row 96 : 1/21/2022 11:47 | CUB - online payment | Other | nan | From vicky | 200.0 | Income | nan | 200.0 | INR | 200.0
row 97 : 1/19/2022 14:27 | CUB - online payment | Food | nan | Lunch + chocolate for preethi | 171.0 | Expense | nan | 171.0 | INR | 171.0
row 98 : 1/18/2022 20:54 | CUB - online payment | Food | nan | Dinner | 301.15 | Expense | nan | 301.15 | INR | 301.15
row 99 : 1/18/2022 17:10 | CUB - online payment | Food | nan | Snack with preethi | 59.0 | Expense | nan | 59.0 | INR | 59.0
row 100 : 1/18/2022 13:51 | CUB - online payment | Food | nan | Lunch with company | 148.0 | Expense | nan | 148.0 | INR | 148.0
row 101 : 1/18/2022 12:59 | CUB - online payment | Other | nan | To kumara | 200.0 | Expense | nan | 200.0 | INR | 200.0
row 102 : 1/18/2022 12:59 | CUB - online payment | Other | nan | From dad | 1000.0 | Income | nan | 1000.0 | INR | 1000.0
row 103 : 1/17/2022 18:31 | CUB - online payment | Food | nan | Eve snack | 100.0 | Expense | nan | 100.0 | INR | 100.0
row 104 : 1/15/2022 21:17 | CUB - online payment | Transportation | nan | Bus to Bangalore | 1365.0 | Expense | nan | 1365.0 | INR | 1365.0
row 105 : 1/15/2022 21:16 | CUB - online payment | Other | nan | From dad | 1500.0 | Income | nan | 1500.0 | INR | 1500.0
row 106 : 1/15/2022 21:16 | CUB - online payment | Food | nan | Snacks | 70.0 | Expense | nan | 70.0 | INR | 70.0
row 107 : 1/14/2022 16:58 | CUB - online payment | Other | nan | Kumara | 170.0 | Income | nan | 170.0 | INR | 170.0
row 108 : 1/14/2022 16:56 | CUB - online payment | Other | nan | Siva + 100 cash | 70.0 | Income | nan | 70.0 | INR | 70.0
row 109 : 1/14/2022 16:56 | CUB - online payment | Other | nan | Gundan + prasanna | 340.0 | Income | nan | 340.0 | INR | 340.0
row 110 : 1/14/2022 16:55 | CUB - online payment | Other | nan | Dinesh and maddy + 100 cash | 240.0 | Income | nan | 240.0 | INR | 240.0
row 111 : 1/14/2022 16:54 | CUB - online payment | Other | nan | From gowdham | 340.0 | Income | nan | 340.0 | INR | 340.0
row 112 : 1/14/2022 16:54 | CUB - online payment | Food | nan | Lunch pongal | 1530.0 | Expense | nan | 1530.0 | INR | 1530.0
row 113 : 1/13/2022 20:46 | CUB - online payment | Food | nan | Dinner | 66.0 | Expense | nan | 66.0 | INR | 66.0
row 114 : 1/13/2022 19:10 | CUB - online payment | Other | nan | From dad | 1000.0 | Income | nan | 1000.0 | INR | 1000.0
row 115 : 1/13/2022 17:47 | CUB - online payment | Transportation | nan | Rapido to pg | 43.0 | Expense | nan | 43.0 | INR | 43.0
row 116 : 1/12/2022 22:44 | CUB - online payment | Other | nan | Recharge by gowdham | 479.0 | Expense | nan | 479.0 | INR | 479.0
row 117 : 1/12/2022 13:25 | CUB - online payment | Food | nan | Pizza | 301.75 | Expense | nan | 301.75 | INR | 301.75
row 118 : 1/12/2022 13:25 | CUB - online payment | Other | nan | From kumara | 200.0 | Income | nan | 200.0 | INR | 200.0
row 119 : 1/11/2022 14:07 | CUB - online payment | Food | nan | Lunch with not preethi | 135.5 | Expense | nan | 135.5 | INR | 135.5
row 120 : 1/10/2022 14:04 | CUB - online payment | Food | nan | Friday snacks with preethi gang | 106.0 | Expense | nan | 106.0 | INR | 106.0
row 121 : 1/8/2022 13:46 | CUB - online payment | Other | nan | From gowdham | 260.0 | Income | nan | 260.0 | INR | 260.0
row 122 : 1/8/2022 13:45 | CUB - online payment | Food | nan | Lunch with gowdham | 535.3 | Expense | nan | 535.3 | INR | 535.3
row 123 : 1/8/2022 13:38 | CUB - online payment | Household | nan | Rent | 4580.0 | Expense | nan | 4580.0 | INR | 4580.0
row 124 : 1/7/2022 13:51 | CUB - online payment | Food | nan | Coffee + biscuit | 15.0 | Expense | nan | 15.0 | INR | 15.0
row 125 : 1/6/2022 21:30 | CUB - online payment | Other | nan | From barath and shakur | 440.0 | Income | nan | 440.0 | INR | 440.0
row 126 : 1/6/2022 20:58 | CUB - online payment | Food | nan | Ketch up | 20.0 | Expense | nan | 20.0 | INR | 20.0
row 127 : 1/6/2022 20:13 | CUB - online payment | Food | nan | Dinner with roommate | 877.81 | Expense | nan | 877.81 | INR | 877.81
row 128 : 1/6/2022 14:22 | CUB - online payment | Food | nan | Bingo | 10.0 | Expense | nan | 10.0 | INR | 10.0
row 129 : 1/6/2022 11:48 | CUB - online payment | Transportation | nan | Rapido to pg | 42.0 | Expense | nan | 42.0 | INR | 42.0
row 130 : 1/5/2022 20:23 | CUB - online payment | Food | nan | McDonald's with company | 211.0 | Expense | nan | 211.0 | INR | 211.0
row 131 : 1/5/2022 14:46 | CUB - online payment | Other | nan | Lended money returned to vishnu | 40.0 | Expense | nan | 40.0 | INR | 40.0
row 132 : 1/5/2022 14:42 | CUB - online payment | Other | nan | Lended money returned to kumara | 30.0 | Expense | nan | 30.0 | INR | 30.0
row 133 : 1/5/2022 14:42 | CUB - online payment | Food | nan | Jan 2nd with shakur and barath | 354.0 | Expense | nan | 354.0 | INR | 354.0
row 134 : 1/5/2022 14:39 | CUB - online payment | Other | nan | To gobi 1st 1/4th | 500.0 | Expense | nan | 500.0 | INR | 500.0
row 135 : 1/5/2022 14:37 | CUB - online payment | Other | nan | To abijith and to vicky lend money returned | 500.0 | Expense | nan | 500.0 | INR | 500.0
row 136 : 1/5/2022 14:35 | CUB - online payment | Transportation | nan | Refund for bus ticket | 60.0 | Expense | nan | 60.0 | INR | 60.0
row 137 : 1/5/2022 14:30 | CUB - online payment | Food | nan | Lunch with company | 388.0 | Expense | nan | 388.0 | INR | 388.0
row 138 : 1/4/2022 22:11 | CUB - online payment | Education | nan | Arrear and reval fee | 1400.0 | Expense | nan | 1400.0 | INR | 1400.0
row 139 : 1/4/2022 22:10 | CUB - online payment | Salary | nan | Salary | 8000.0 | Income | nan | 8000.0 | INR | 8000.0
row 140 : 1/4/2022 13:53 | CUB - online payment | Food | nan | Lunch with company | 106.0 | Expense | nan | 106.0 | INR | 106.0
row 141 : 1/4/2022 8:01 | CUB - online payment | Other | nan | To vicky | 80.0 | Expense | nan | 80.0 | INR | 80.0
row 142 : 1/4/2022 7:58 | CUB - online payment | Food | nan | Sent to preethi | 107.0 | Expense | nan | 107.0 | INR | 107.0
row 143 : 1/3/2022 22:15 | CUB - online payment | Food | nan | Dairy milk | 10.0 | Expense | nan | 10.0 | INR | 10.0
row 144 : 1/3/2022 21:54 | CUB - online payment | Other | nan | From barath | 201.0 | Income | nan | 201.0 | INR | 201.0
row 145 : 1/3/2022 21:12 | CUB - online payment | Other | nan | From gpay | 5.0 | Income | nan | 5.0 | INR | 5.0
row 146 : 1/3/2022 21:11 | CUB - online payment | Other | nan | From shakur | 140.0 | Income | nan | 140.0 | INR | 140.0
row 147 : 1/3/2022 14:31 | CUB - online payment | Food | nan | Lunch unlimited nv | 300.0 | Expense | nan | 300.0 | INR | 300.0
row 148 : 1/3/2022 14:30 | CUB - online payment | Other | nan | From abi | 300.0 | Income | nan | 300.0 | INR | 300.0
row 149 : 1/2/2022 20:33 | CUB - online payment | Other | nan | Tablet to gowdham | 8.0 | Expense | nan | 8.0 | INR | 8.0
row 150 : 1/2/2022 20:32 | CUB - online payment | Food | nan | Dinner with barath | 200.0 | Expense | nan | 200.0 | INR | 200.0
row 151 : 1/2/2022 14:16 | CUB - online payment | Transportation | nan | Train to vnr | 725.0 | Expense | nan | 725.0 | INR | 725.0
row 152 : 1/1/2022 21:46 | CUB - online payment | Food | nan | Snacks | 85.0 | Expense | nan | 85.0 | INR | 85.0
row 153 : 1/1/2022 21:45 | CUB - online payment | Allowance | nan | From dad | 1000.0 | Income | nan | 1000.0 | INR | 1000.0
row 154 : 12/30/2021 14:10 | CUB - online payment | Food | nan | To barath | 20.0 | Expense | nan | 20.0 | INR | 20.0
row 155 : 12/30/2021 13:56 | CUB - online payment | Transportation | nan | Pg to office | 43.0 | Expense | nan | 43.0 | INR | 43.0
row 156 : 12/30/2021 13:36 | CUB - online payment | Other | nan | From kumara | 30.0 | Income | nan | 30.0 | INR | 30.0
row 157 : 12/30/2021 12:43 | CUB - online payment | Food | nan | Horlicks + kolakattai | 25.0 | Expense | nan | 25.0 | INR | 25.0
row 158 : 12/30/2021 12:38 | CUB - online payment | Transportation | nan | Bommasandra to pg | 199.0 | Expense | nan | 199.0 | INR | 199.0
row 159 : 12/30/2021 12:37 | CUB - online payment | Other | nan | From Deepak | 250.0 | Income | nan | 250.0 | INR | 250.0
row 160 : 12/30/2021 11:45 | CUB - online payment | Food | nan | Water | 20.0 | Expense | nan | 20.0 | INR | 20.0

TypeError: 'NoneType' object is not subscriptable

In [47]:
# Use the custom LLM with OpenRouter settings
llm = OpenRouterOpenAI(model="liquid/lfm-40b:free")

# Initialize and query the ChainOfTableQueryEngine
query_engine = ChainOfTableQueryEngine(df, llm=llm, verbose=True)
response = query_engine.query("Who won best Director in the 1972 Academy Awards?")
print(response)

AttributeError: 'OpenRouterOpenAI' object has no attribute 'callback_manager'

In [34]:
from openai import OpenAI
from os import getenv

# gets API Key from environment variable OPENAI_API_KEY
client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key="",
)

completion = client.chat.completions.create(
  model="liquid/lfm-40b:free",
  messages=[
    {
      "role": "user",
      "content": "What is the meaning of life?"
    }
  ]
)
print(completion.choices[0].message.content)

The meaning of life has been a topic of philosophical debate and introspection for centuries. Its meaning can vary among different cultures, religions, and individuals. Many people seek purpose in their lives through accomplishments, relationships, personal growth, or fulfillment of dreams. Some may believe in a spiritual or divine purpose, while others embrace existentialist philosophies. It's a deeply personal, often subjective question, with no universally agreed-upon answer.